.\" -*- nroff -*-
.TH FV 1 "2023-01-28" "fv version 4"
.SH NAME
fv \- archive and package directory lister
.SH SYNOPSIS
.B fv
[
.B \-v
]
[
.B \-?
]
[
.B \-h
]
[
.B \-l
]
[
.B \-t
type ]
archive1
[
.I archive2 ...
]
.SH DESCRIPTION
.B fv
is a wrapper around the file list functions of most common kinds of
archivers and packagers available on *NIX systems. It provides a fast,
easy way to look inside archives without having to remember the arcane
options required by many archiving programs.
.LP
The archive type is determined from the filename suffix (unless the
.B \-t
option is given), which selects which archiver program to run.
The archiver's `list archive contents' arguments are given to display
a directory containing the most generally useful information about the files
within the archive. The archive must be in a file; it cannot be given on
standard input.
.LP
If the program which is needed to handle an archive type is not available
on the system, the error message \(lqcommand not found\(rq is
displayed as it is encountered.  The error message \(lqNot a known
archive format\(rq is displayed for unknown suffixes.
.LP
Several archive types do not have common file suffixes, so arbitrary but
unique suffixes are used.  A few file extensions are ambiguous and could
refer to more than one type.  The \-t option can be used in such cases to
force decoding as an alternate type.  To find the complete list of archive
types and suffixes supported, execute
.B fv
with the \-l option.
This version supports the following file extensions:
.LP
.\" This section comes from: ./fv -l | sed -e /^Supported/,1d -e 's/^/.SM /'
.SM .3mf .7z .a .ace .alz .apk .apkm .AppImage .application .arc .arj .bun
.SM .bxy .bz2 .cab .cbmarc .ccs .cf .cgz .chm .chrt .cpio .cpio.bz2 .cpio.gz
.SM .cpio.Z .cpio.z .d64 .dar .dat .deb .depot .depot.gz .dmg .docm .docx
.SM .egg .epk .epub .f3d .flw .fpm .gem .gz .ha .hp .hqx .ipg .ipk .iso .jar
.SM .jffs2 .kfo .kgb .kil .kmz .kpr .kra .ksp .kwd .lbr .lha .lnx .lpkg .lz
.SM .lzh .lzma .lzo .mac .mar .msi .n64 .nif .nth .odb .odc .odf .odg .odp
.SM .ods .odt .onepkg .opk .ora .otg .otp .ots .par .par2 .pbi .pdf .pet .pisi
.SM .pk3 .pkg .pptx .pq6 .pup .qpk .qpr .rar .resource .rpm .rpp .rsn .rub
.SM .rz .sa .sb2 .sb3 .sda .sdk .sfx .sh .sh2 .shar .shk .sis .sit .slp .snap
.SM .spark .spm .sqsh .squashfs .sto .sxd .sxi .sxm .sxw .t64 .tar .tar.bz2
.SM .tar.gz .tar.lz .tar.lzma .tar.xz .tar.Z .tar.z .tar.zst .tardist .taz
.SM .tbz .tbz2 .tc .tgz .tlz .txz .uRamdisk .uu .uua .uue .wacz .wad .wal
.SM .war .wfp .whl .wsz .x64 .xar .xlsx .xpi .xps .xz .Z .z .zip .zoo .zpaq
.SM .zst .zz .[psrud]00 winmail.dat
.\" End of mechanically-generated section
.LP
Not all files supported are strictly archive types; several structured
documents formats are also supported.  Most of these are build on
existing archive formats and can be explored using standard archive tools.
.LP
It is trivial to add more file types to
.BR fv .
Please contact the author if you know of one not included.
.LP
These are the file types supported:
.LP
.RS
.\" This section comes from: ./fv -v -l | sed a.LP
(unknown 3D package)
.LP
3-D Manufacturing format
.LP
7zip archive
.LP
ACE archive
.LP
Allegro4 not packed datafile
.LP
ALZ archive
.LP
Android package
.LP
Apkmirror Android package
.LP
AppImage package
.LP
Apple disk image
.LP
Apple II archive
.LP
ar archive
.LP
Archimedes Spark archive (RiscOS)
.LP
ARJ archive
.LP
BUN archive
.LP
bzip2-compressed cpio archive
.LP
bzip2-compressed file
.LP
bzip2-compressed tar archive
.LP
Commodore 64 archive
.LP
Compound File Compiler archive
.LP
compressed cpio archive
.LP
Conary Change Set
.LP
CP/M LBR archive
.LP
cpio archive
.LP
Debian distribution archive
.LP
Disk Archiver archive
.LP
Doom WAD archive
.LP
eCos package
.LP
EPub Document
.LP
Frugalware package
.LP
Google Earth
.LP
gzip-compressed file
.LP
gzip-compressed tar archive
.LP
ha archive
.LP
HP-UX package
.LP
HP48 distribution archive as posted to comp.sources.hp48
.LP
iPod Game
.LP
ISO9660 filesystem image file
.LP
Itsy package
.LP
Java jar file
.LP
Java Web Start
.LP
JFFS2 filesystem image file
.LP
KChart Chart
.LP
KFormula Document
.LP
KGB archive
.LP
Kivio Document
.LP
Kontour Illustration
.LP
KPresenter Document
.LP
Krita image
.LP
KSpread Spreadsheet
.LP
KWord Document
.LP
LHARC archive
.LP
Lua package
.LP
LZIP compressed file
.LP
lzip-compressed tar archive
.LP
LZMA compressed file
.LP
LZMA compressed tar archive
.LP
LZOP compressed file
.LP
Macintosh BinHex encoding
.LP
Macintosh MacBinary encoding
.LP
Macintosh StuffIt archive
.LP
Meta Archive
.LP
Microsoft Cabinet archive
.LP
Microsoft Compressed HTML
.LP
Microsoft Installer
.LP
Microsoft Office Open XML document
.LP
Microsoft Office Open XML document with Macros
.LP
Microsoft Office Open XML presentation
.LP
Microsoft Office Open XML spreadsheet
.LP
Microsoft OneNote package
.LP
Microsoft TNEF e-mail attachment
.LP
Mozilla Java Cross Platform Installer
.LP
Netscape package
.LP
Nokia mobile phone theme
.LP
OpenDocument Chart
.LP
OpenDocument Database
.LP
OpenDocument Document
.LP
OpenDocument Drawing
.LP
OpenDocument Drawing Template
.LP
OpenDocument Formula
.LP
OpenDocument Presentation
.LP
OpenDocument Presentation Template
.LP
OpenDocument Spreadsheet
.LP
OpenDocument Spreadsheet Template
.LP
OpenMoko package
.LP
OpenOffice Drawing
.LP
OpenOffice Impress Presentation
.LP
OpenOffice Math
.LP
OpenOffice Writer Document
.LP
OpenRaster image
.LP
PAQ6 compressed archive
.LP
Pardus package
.LP
Parity Archive ver. 2
.LP
PC-BSD package
.LP
Perl package
.LP
Portable Document Format document
.LP
Puppy Linux Extra Treats package
.LP
Puppy Linux package
.LP
Python package
.LP
Python wheel package
.LP
QNX package
.LP
QNX package archive
.LP
Quake3 packed file
.LP
RAR compressed archive
.LP
Red Hat RPM package
.LP
Red Hat RPP package
.LP
Rubix package
.LP
Ruby package
.LP
rzip archive
.LP
Scratch Project
.LP
SEA ARC archive
.LP
shell archive
.LP
Snap package
.LP
SNES sound archive
.LP
Squashfs filesystem image
.LP
Stampede Linux package
.LP
stopmotion movie
.LP
Syllable application package
.LP
Syllable resource package
.LP
SymbianOS SIS installable package
.LP
SysV package (SCO UNIX, IRIX)
.LP
tar archive
.LP
tardist IRIX package
.LP
Tellico database
.LP
Tukaani Linux package
.LP
U-boot ramdisk image
.LP
uuencoded file
.LP
Web Archive Collection Zipped
.LP
Winamp compressed skin file
.LP
Wondershare Filmora Project
.LP
XAR archive
.LP
XML Paper Specification
.LP
xz-compressed file
.LP
xz-compressed tar archive
.LP
ZIP archive
.LP
ZOO archive
.LP
ZPAQ compressed archive
.LP
zstd-compressed file
.LP
zstd-compressed tar archive
.LP
ZZIP archive
.LP
.\" End of mechanically-generated section
.RE
.\" ---------------------------------------------------------------------------
.SH OPTIONS
.TP
.B "\-? \-h"
Show the
.B fv
help information (this also appears if
.B fv
is run with no arguments).
.TP
.B \-l
Display a list of the file extensions supported.
.TP
.BI \-t \ type
Use
.I type
as the archive type (extension) instead of determining it from the file name.
.TP
.B \-v
Set verbose mode. Display the type of archive before the listing.  If \-l is
also given, display a description of each archive type supported instead of
the file extensions.  If two \-v options are given, the archive command
is displayed as it is executed.
.\" ---------------------------------------------------------------------------
.SH EXAMPLES
View the list of files contained in a ZIP archive:
.EX
fv file.zip
.EE
.LP
View the list of files embedded in a PDF file and see what commands are
executed to do so:
.EX
fv -v -v complicated.pdf
.EE
.LP
View the contents of a CD-ROM using its device name:
.EX
fv \-t iso /dev/cdrom
.EE
.LP
View a spark file that shares the same extension as a SEA ARC file:
.EX
fv \-t spark file.arc
.EE
.\" ---------------------------------------------------------------------------
.SH "EXIT STATUS"
.B fv
returns the the exit code of the archive listing program, which may be zero
even in case of error in some cases.  If the archive type is unsupported
it returns 1 and if no arguments are given it returns 3.
.\" ---------------------------------------------------------------------------
.SH BUGS
.BR fv 's
command-line option processing is very limited; the order which options appear
is significant and only one option may follow each -.
.\" ---------------------------------------------------------------------------
.SH AUTHOR
Daniel Fandrich <dan@coneharvesters.com>
.LP
See https://github.com/dfandrich/fileviewinfo/
.LP
.B fv
was inspired by the late Vernon D. Buerg's program
.I fv
for displaying directories of MS-DOS archives.
.\" ---------------------------------------------------------------------------
.SH COPYRIGHT
.B fv
is placed into the public domain by Daniel Fandrich.
See the file COPYING for details of how CC0 applies to this file.
.\" ---------------------------------------------------------------------------
.SH "SEE ALSO"
.B fv
is similar in concept to
.BR als (1),
part of the atool package
(see https://www.nongnu.org/atool/).
The
.BR extractcode (1)
program (part of ScanCode, see https://github.com/nexB/scancode-toolkit/)
similarly extracts files from many archive formats instead of merely listing
them.
