.\" -*- nroff -*-
.TH FVI 1 "2024-01-10" "fvi version 8-dev"
.SH NAME
fvi \- File view info metadata displayer
.SH SYNOPSIS
.B fvi
[
.B \-v
]
[
.B \-?
]
[
.B \-h
]
[
.B \-l
]
[
.B \-t
type ]
file1
[
.I file2 ...
]
.SH DESCRIPTION
.B fvi
is a wrapper around many file metadata display programs available on *NIX
systems. It provides a quick way to display metadata about a file without
without having to remember which program is the right one to use for each type.
.LP
The file type is determined from the filename suffix (unless the
.B \-t
option is given), which selects which information viewing program to run.
The file argument must point to an actual filename; the file contents cannot be
given on standard input.
.LP
If the program which is needed to display information is not available
on the system, the error message \(lqcommand not found\(rq is
displayed as it is encountered.  The error message \(lqUnsupported file
format.\(rq is displayed for unknown suffixes.
.LP
To find the complete list of file types and suffixes supported, execute
.B fvi
with the \-l option.
This version supports the following file extensions:
.LP
.\" This section comes from: ./fvi -l | sed -e /^Supported/,1d -e 's/^/.SM /'
.SM .3g2 .3gp .3mf .4xm .5vw .5vw.gz .7z .a .aac .ac3 .adts .aiff .alaw .amf
.SM .amr .amv .apc .ape .apk .apkm .application .asf .asf_stream .au .avi .avs
.SM .bethsoftvid .bfr .bfr.gz .bochs .bpb .bz2 .c93 .cacrt .cap .cap.gz .cfi
.SM .cgm .cgz .chrt .class .cpm .crc .crl .crt .csr .d2m .d4m .d80 .d81 .d88
.SM .dar .daud .db .deb .depot .depot.gz .der .dex .dfi .dirac .dll .dmg .dmk
.SM .dng .docm .docx .ds2 .dsc .dsicin .dsk .dtb .dti .dts .dv .dv1394 .dvd
.SM .dxa .dylib .ea .edsk .egg .epk .eps .epub .erf .erf.gz .exe .f3d .fdi
.SM .ffm .fig .film_cpk .flac .flic .flv .flw .fpm .fpx .framecrc .gdbm .gif
.SM .gmo .gpg .gplt .gpx .gxf .gz .h261 .h263 .h264 .heic .heic .heif .hfe
.SM .hpgl .idcin .image2 .image2pipe .imd .ingenient .ipf .ipg .ipk .ipmovie
.SM .iso .jar .jbig .jfif .jp2 .jpeg .jpg .key .kfo .kil .kmz .kpr .kra .ksp
.SM .kwd .libnut .lif .lz .lzma .lzo .m1v .m2v .m4a .m4v .matroska .mbd .mgt
.SM .mj2 .mjpeg .mkv .mm .mmf .mng .mo .mov .mp2 .mp3 .mp4 .mpc .mpe .mpeg
.SM .mpeg1video .mpeg2video .mpegts .mpegtsraw .mpegvideo .mpg .mpg4 .mpjpeg
.SM .mport .msa .mscz .mts .MTV .mulaw .mxf .ncf .ncf.gz .ncfx .ncfx.gz .nif
.SM .nsv .nth .null .nut .nuv .o .odf .odg .odp .ods .odt .ogg .ogv .opd
.SM .opk .oss .otf .otg .otp .ots .pam .par .parallels .pbm .pcap .pcap.gz
.SM .pcapng .pcapng.gz .pcl .pcx .pdf .pem .pet .pfa .pfb .pgm .pgp .pk3
.SM .png .pnm .po .ppm .pptx .ps .psp .psxstr .pyc .pyd .pyo .qcow .qcow2
.SM .qed .qpk .qpr .qt .ram .rar .raw .rawvideo .redir .resource .rle .rm
.SM .RoQ .rpm .rsn .rtp .rtsp .rub .rz .s16be .s16le .s24 .s8 .sad .sb2 .sb3
.SM .sbt .scl .scp .sdf .sdp .shn .siff .sig .sis .slob .slp .smk .snap
.SM .snoop .snoop.gz .so .so.?  .so.??  .so.???  .sol .spm .sqfs .sqlite
.SM .sqlite3 .sqsh .squashfs .stl .svcd .svg .svgz .swf .sxd .sxi .sxm .sxw
.SM .taz .tbz .tbz2 .tc .tc-compressed .td0 .tdb .tgz .thp .tiertexseq .tif
.SM .tiff .tlz .torrent .tr1 .tr1.gz .trc0 .trc0.gz .trd .tta .ttf .txd .txz
.SM .typelib .u16be .u16le .u8 .udi .vc1 .vcd .vdi .vhd .vhdx .video4linux
.SM .video4linux2 .vmd .vmdk .vob .voc .vpc .wacz .wal .war .warc.gz .wav
.SM .wc3movie .webm .webp .whl .wmf .wmv .wmz .woff .wsaud .wsvqa .wsz .wv
.SM .x11grab .xbm .xlsx .xpi .xpm .xps .xz .yuv4mpegpipe .Z .z .zip .zst gz
.SM xz zst
.\" End of mechanically-generated section
.LP
It is trivial to add more file types to
.BR fvi .
Please contact the author if you know of one not included.
.LP
These are the file types supported:
.LP
.RS
.\" This section comes from: ./fvi -v -l | sed -e a.LP -e 's/^\./\\\&./'
(unknown 3D package)
.LP
3MF 3-D Manufacturing file
.LP
7zip archive
.LP
Additive Manufacturing File
.LP
Android Java class file
.LP
Android package
.LP
Apkmirror Android package
.LP
Berkeley Database
.LP
Binary message catalog file
.LP
Bitmapped image file
.LP
BitTorrent torrent file
.LP
bzip2-compressed file
.LP
bzip2-compressed tar archive
.LP
CFI floppy disk image
.LP
Compressed Scalable Vector Graphic image file
.LP
Compressed Web Archive Collection file
.LP
Debian distribution archive
.LP
DER certificate
.LP
Device Tree Binary file
.LP
Digital Negative Raw Image
.LP
Disk Archiver archive
.LP
EPub Document
.LP
FLAC audio
.LP
Floppy disk image
.LP
Floppy disk image file
.LP
Font file
.LP
G-IR binary database
.LP
GDBM database
.LP
GIF image
.LP
Gnu Privacy Guard/Pretty Good Privacy file
.LP
GnuPG
.LP
Google Earth
.LP
GPS exchange format file
.LP
gzip-compressed file
.LP
HEIF image
.LP
HP-UX package
.LP
iPod Game
.LP
ISO9660 filesystem image file
.LP
Itsy package
.LP
Java compiled class file
.LP
Java jar file
.LP
Java Web Start
.LP
JPEG image
.LP
Krita image
.LP
lzip-compressed file
.LP
LZMA compressed file
.LP
LZOP-compressed file
.LP
Mac OS X Disk Image
.LP
Mach dynamic library
.LP
Matroska video file
.LP
Microsoft Audio Video Interleaved
.LP
Microsoft Office Open XML
.LP
Microsoft Office Open XML with Macros
.LP
Midnight BSD ports package
.LP
Mozilla Java Cross Platform Installer
.LP
MP3 audio file
.LP
MPEG video
.LP
Multiple-image Network Graphics file
.LP
MuseScore music score
.LP
Nokia mobile phone theme
.LP
Object file/archive
.LP
OGG audio/video
.LP
OpenDocument
.LP
OpenDocument Drawing
.LP
OpenDocument Drawing Template
.LP
OpenDocument Formula
.LP
OpenDocument Presentation
.LP
OpenDocument Presentation Template
.LP
OpenDocument Spreadsheet
.LP
OpenDocument Spreadsheet Template
.LP
OpenMoko package
.LP
OpenOffice Drawing
.LP
OpenOffice Impress Presentation
.LP
OpenOffice Math
.LP
OpenOffice Writer Document
.LP
Pcap network capture file
.LP
PEM certificate
.LP
Perl package
.LP
Portable Document Format document
.LP
Portable Network Graphics image
.LP
Portable pixmap image
.LP
Private key
.LP
Python compiled file
.LP
Python egg package
.LP
Python wheel package
.LP
QEMU disk image
.LP
Quake3 packed file
.LP
Quicktime audio
.LP
Quicktime video
.LP
RAR compressed archive
.LP
Red Hat RPM package
.LP
rzip archive
.LP
Scratch Project
.LP
Shockwave Flash file
.LP
Snap package
.LP
Sorted List of Blobs dictionary
.LP
Sqlite database file
.LP
Squashfs filesystem image
.LP
Stampede Linux package
.LP
STL model file
.LP
Syllable application package
.LP
Syllable resource package
.LP
SymbianOS SIS installable package
.LP
Tagged Image File Format image
.LP
tc-compressed file
.LP
TDB database file
.LP
Tellico database
.LP
Text message catalog file
.LP
Tukaani Linux package
.LP
URPM synthesis file
.LP
Vector image file
.LP
Video or audio file
.LP
VirtualBox disk image
.LP
WAV audio file
.LP
Web Archive Collection Zipped
.LP
Winamp compressed skin file
.LP
Windows Media compressed skin file
.LP
Windows PE Dynamic Link Library
.LP
Windows PE executable
.LP
X.509 CA certificate
.LP
X.509 certificate
.LP
X509 Certificate Signing Request
.LP
X509 CRL
.LP
XML Paper Specification
.LP
XZ compressed file
.LP
xz-compressed tar archive
.LP
ZIP archive
.LP
zstd-compressed file
.LP
.\" End of mechanically-generated section
.RE
.\" ---------------------------------------------------------------------------
.SH OPTIONS
.TP
.B "\-? \-h"
Show the
.B fvi
help information (this also appears if
.B fvi
is run with no arguments).
.TP
.B \-l
Display a list of the file extensions supported.
.TP
.BI \-t \ type
Use
.I type
as the file type (extension) instead of determining it from the file name.
.TP
.B \-v
Set verbose mode. Display the type of file before the listing.  If \-l is
also given, display a description of each file type supported instead of
the file extensions.  If two \-v options are given, the file info display
command is displayed as it is executed.
.\" ---------------------------------------------------------------------------
.SH EXAMPLES
View information about a ZIP archive:
.EX
fvi file.zip
.EE
.LP
View information about a Gnu DBM file that shares an extension with a Berkeley
database file:
.EX
fvi -t gdbm index.db
.EE
.LP
Use an alternate program to view information about an MPEG-4 video:
.EX
fvi -t ffm file.mp4
.EE
.\" ---------------------------------------------------------------------------
.SH "EXIT STATUS"
.B fvi
returns the the exit code of the file info display program, which may be zero
even in case of error in some cases.  If the file type is unsupported
it returns 1 and if no arguments are given it returns 3.
.\" ---------------------------------------------------------------------------
.SH BUGS
.BR fvi 's
command-line option processing is very limited; the order which options appear
is significant and only one option may follow each -.
.\" ---------------------------------------------------------------------------
.SH AUTHOR
Daniel Fandrich <dan@coneharvesters.com>
.LP
See https://github.com/dfandrich/fileviewinfo/
.\" ---------------------------------------------------------------------------
.SH COPYRIGHT
.B fvi
is Copyright (c) 2021\(en2024 Dan Fandrich <dan@coneharvesters.com>.
Licensed under the MIT license (see LICENSE).
