# Github Actions configuration
name: CI

permissions: {}

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master and ci branches
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master

jobs:
  build-22_04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: 'Install deps'
      run: >
        sudo apt-get update -y &&
        sudo apt-get install -y --no-install-suggests --no-install-recommends
        arj
        binutils
        bsdextrautils
        cabextract
        calibre
        cpio
        exif
        exiftool
        ffmpeg
        file
        flac
        freetype2-demos
        genisoimage
        gettext
        gifsicle
        gimp
        openjdk-18-jdk-headless
        jq
        lhasa
        liballegro4-dev
        libavifile-0.7-bin
        libid3-tools
        libjpeg-turbo-progs
        libtiff-tools
        lzop
        man-db
        mkvtoolnix
        mtd-utils
        netpbm
        p7zip-full
        pngtools
        poppler-utils
        python3-dateutil
        python3-minimal
        python3-vobject
        quicktime-utils
        rar
        rpm
        squashfs-tools
        unzip
        vorbis-tools
        wireshark-common
        xmlstarlet
        zpaq
        make curl ca-certificates groff-base man2html-base bash busybox ksh yash zsh
    - name: 'Install extras'
    # A few packages need newer versions to work properly, so install them
    # separately.
      run: |
        curl -LsSf --retry 6 --retry-connrefused --max-time 999 --remote-name-all \
            http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/pngtools/pngtools_0.5~git20220314.1ccca3a-2ubuntu1_amd64.deb \
            http://azure.archive.ubuntu.com/ubuntu/pool/universe/n/netpbm-free/netpbm_11.01.00-2build1_amd64.deb \
            http://azure.archive.ubuntu.com/ubuntu/pool/universe/n/netpbm-free/libnetpbm11_11.01.00-2build1_amd64.deb \
            http://azure.archive.ubuntu.com/ubuntu/pool/universe/r/rust-coreutils/rust-coreutils_0.0.17-2_amd64.deb
        test "$(sha256sum pngtools_0.5~git20220314.1ccca3a-2ubuntu1_amd64.deb)" = "1c7490f01a64af135d6341b8e5a9ab2fc94dcfe99131882cef1e623739bfadc6  pngtools_0.5~git20220314.1ccca3a-2ubuntu1_amd64.deb"
        test "$(sha256sum netpbm_11.01.00-2build1_amd64.deb)" = "ee102926ef4289c0830092447d650a58a48a0d136cab268af52b55d81d6485ce  netpbm_11.01.00-2build1_amd64.deb"
        test "$(sha256sum libnetpbm11_11.01.00-2build1_amd64.deb)" = "d690a886c1ff250ebca438d7fa64f0a6f9f56a1543c312b503ed3209a56efda3  libnetpbm11_11.01.00-2build1_amd64.deb"
        test "$(sha256sum rust-coreutils_0.0.17-2_amd64.deb)" = "f34842f12753527bdc7fac8595dc91e9aede0296348dd556614a3580811e4a06  rust-coreutils_0.0.17-2_amd64.deb"
        sudo dpkg -i pngtools*.deb netpbm*.deb libnetpbm*.deb rust-coreutils*.deb || true Ignore missing dependency errors--they are not needed for our tests
        # unrar isn't installed in /usr/bin for some reason
        sudo install -m0755 -D /usr/lib/unrar -t /usr/local/bin
    - name: 'Patch tests'
      # lhasa isn't a perfect substitute for lha until post-v0.3.1
      run: sed -i '/type1.lzh/d' test-automtime-expected
    - name: 'Run tests'
      run: make check -k
    - name: 'Run tests with ash'
      run: make check -k SHELL='busybox ash'
    - name: 'Run tests with bash'
      run: make check -k SHELL=bash
    - name: 'Run tests with dash'
      run: make check -k SHELL=dash
    - name: 'Run tests with ksh'
      run: make check -k SHELL=ksh
    - name: 'Run tests with yash'
      run: make check -k SHELL=yash
    - name: 'Run tests with zsh'
      run: make check -k SHELL=zsh
    - name: 'Prepare for uutils-coreutils'
      run: sudo rm /usr/lib/cargo/bin/coreutils/date  # buggy up to 0.0.17
    - name: 'Run tests using uutils-coreutils'
      run: PATH="/usr/lib/cargo/bin/coreutils:$PATH" make check -k
    - name: 'Prepare for Busybox'
      run: |
        mkdir -p "$PWD/bb"
        busybox --install -s "$PWD/bb"
        # These Busybox applets don't have the required features, so the native
        # applications are needed instead.
        rm -f "$PWD"/bb/{lzop,rpm,tar,unzip}
        # Time zone output is different when using the fallback date routine
        # that's used when Busybox 'date' is in use. All the lines are
        # equivalent; only the time zone representation differs.
        sed -i \
          -e 's/2023-01-06 02:15:02 +0000/2023-01-05 21:15:02 -0500/' \
          -e 's/2021-10-13 08:02:00 +0000/2021-10-13 01:02:00 -0700/' \
          -e 's/2021-10-18 16:55:54 +0000/2021-10-18 16:55:54/' \
          test-automtime-expected
    - name: 'Run tests using Busybox'
      run: PATH="$PWD/bb:$PATH" make check -k SHELL="$PWD/bb/sh"
    - name: 'Build documentation'
      run: make man
    - name: 'Test installation'
      run: make install prefix="$PWD/install"
    - name: 'Test dist'
      run: make dist
    - name: 'Test distclean'
      run: make distclean
